"""Post a workdir's report.md as a comment on the source Jira issue.

This tool DOES NOT RUN unless explicitly invoked by the user. It is never
called automatically by watch_video.py or the orchestrator. The --post-to-jira
flag on watch_video.py is opt-in per run; this standalone script is opt-in
per invocation; and both default to a confirmation prompt before any POST.

Safety stack:
  1. Default off everywhere (watch_video.py won't pass --post-to-jira itself).
  2. --dry-run prints the formatted comment without posting.
  3. Interactive confirmation prompt unless --yes is passed.
  4. Idempotency check: scans recent comments on the ticket for a signature
     that indicates a prior /watch-video post; aborts if found unless --force.
  5. Read-only fallback: any HTTP non-201 -> exit non-zero, no retries.

Usage:
    python post_to_jira.py <workdir> [--jira-key PROJ-X] [--dry-run]
                                     [--yes] [--force]
                                     [--credentials PATH]

The Jira key is read from <workdir>/meta.json's video.issue_key unless
--jira-key is given (which can target a different ticket).
"""
from __future__ import annotations

import argparse
import base64
import json
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _common import ExitCode, die, emit  # noqa: E402


DEFAULT_CREDS_PATH = Path.home() / ".atlassian-token" / "credentials.json"
SIGNATURE = "Generated by `/watch-video`"  # appears in report.md footer


def _load_creds(path: Path) -> dict:
    if not path.exists():
        die(ExitCode.BAD_INPUT,
            f"Atlassian credentials not found at {path}",
            credentials_path=str(path),
            hint="See SKILL.md -> Jira token setup")
    return json.loads(path.read_text(encoding="utf-8"))


def _basic_auth(email: str, token: str) -> str:
    return base64.b64encode(f"{email}:{token}".encode()).decode()


def md_to_adf(md_text: str) -> dict:
    """Minimal markdown-to-ADF converter for Atlassian Cloud comments.

    Handles: # headings (levels 1-6), > blockquotes, image refs as italics,
    --- horizontal rules, blank-line paragraph breaks, plain text. Inline
    formatting (bold, italics, links) is preserved as plain text -- not
    re-marked-up. Good enough for report.md's structure.
    """
    content: list[dict] = []
    para_buf: list[str] = []
    quote_buf: list[str] = []
    in_quote = False

    def flush_para():
        if para_buf:
            text = " ".join(s.strip() for s in para_buf if s.strip())
            if text:
                content.append({
                    "type": "paragraph",
                    "content": [{"type": "text", "text": text}],
                })
            para_buf.clear()

    def flush_quote():
        nonlocal in_quote
        if quote_buf:
            text = " ".join(s.strip() for s in quote_buf if s.strip())
            if text:
                content.append({
                    "type": "blockquote",
                    "content": [{
                        "type": "paragraph",
                        "content": [{"type": "text", "text": text}],
                    }],
                })
            quote_buf.clear()
        in_quote = False

    for raw in md_text.split("\n"):
        line = raw.rstrip()

        # Blank line -- end any open block
        if not line.strip():
            flush_para()
            flush_quote()
            continue

        # Heading
        if line.startswith("#"):
            flush_para()
            flush_quote()
            level = 0
            while level < len(line) and line[level] == "#":
                level += 1
            text = line[level:].strip()
            content.append({
                "type": "heading",
                "attrs": {"level": min(max(level, 1), 6)},
                "content": [{"type": "text", "text": text}],
            })
            continue

        # Horizontal rule
        if line.strip() in ("---", "***", "___"):
            flush_para()
            flush_quote()
            content.append({"type": "rule"})
            continue

        # Blockquote
        if line.startswith(">"):
            flush_para()
            in_quote = True
            quote_buf.append(line.lstrip("> ").rstrip())
            continue

        # Image reference -- preserve as italic text mentioning the filename
        if line.lstrip().startswith("!["):
            flush_quote()
            # Format: ![alt](path)
            content.append({
                "type": "paragraph",
                "content": [{
                    "type": "text",
                    "text": f"[frame: {line.strip()}]",
                    "marks": [{"type": "em"}],
                }],
            })
            continue

        # Plain paragraph line
        if in_quote:
            quote_buf.append(line)
        else:
            para_buf.append(line)

    flush_para()
    flush_quote()

    return {"version": 1, "type": "doc", "content": content}


def fetch_recent_comments(site: str, jira_key: str, auth: str,
                          max_results: int = 50) -> list[dict]:
    url = (f"https://{site}/rest/api/3/issue/{jira_key}/comment"
           f"?maxResults={max_results}&orderBy=-created")
    req = urllib.request.Request(url, headers={
        "Authorization": f"Basic {auth}", "Accept": "application/json",
    })
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.load(resp)
    except urllib.error.HTTPError as e:
        if e.code == 401:
            die(ExitCode.AUTH_FAIL, "Atlassian auth failed (401)")
        if e.code == 404:
            die(ExitCode.BAD_INPUT, f"Issue {jira_key} not found or no access")
        die(ExitCode.IO_FAIL, f"Atlassian API {e.code}: {e.read().decode()[:200]}")
    return data.get("comments", [])


def comment_contains_signature(comment: dict, signature: str) -> bool:
    """Walk a comment's ADF body looking for our signature in any text node."""
    body = comment.get("body")
    if isinstance(body, str):
        return signature in body
    # Walk ADF
    stack = [body]
    while stack:
        node = stack.pop()
        if isinstance(node, dict):
            if node.get("type") == "text" and signature in node.get("text", ""):
                return True
            for child in node.get("content", []) or []:
                stack.append(child)
        elif isinstance(node, list):
            stack.extend(node)
    return False


def post_comment(site: str, jira_key: str, auth: str, adf_body: dict) -> dict:
    url = f"https://{site}/rest/api/3/issue/{jira_key}/comment"
    payload = json.dumps({"body": adf_body}).encode()
    req = urllib.request.Request(url, data=payload, headers={
        "Authorization": f"Basic {auth}",
        "Accept": "application/json",
        "Content-Type": "application/json",
    })
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            return json.load(resp)
    except urllib.error.HTTPError as e:
        body = e.read().decode()[:400]
        if e.code == 401:
            die(ExitCode.AUTH_FAIL, f"Atlassian auth failed posting comment: {body}")
        if e.code == 404:
            die(ExitCode.BAD_INPUT, f"Issue {jira_key} not found or no access: {body}")
        die(ExitCode.IO_FAIL, f"Atlassian comment POST failed {e.code}: {body}")


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Post <workdir>/report.md as a comment on a Jira issue. "
                    "Default safety: confirmation prompt + idempotency check.")
    ap.add_argument("workdir")
    ap.add_argument("--jira-key", default=None,
                    help="override the issue key from meta.json's video.issue_key")
    ap.add_argument("--credentials", default=str(DEFAULT_CREDS_PATH),
                    help="Atlassian credentials JSON path")
    ap.add_argument("--dry-run", action="store_true",
                    help="print the formatted comment + target ticket; do NOT post")
    ap.add_argument("--yes", action="store_true",
                    help="skip the interactive confirmation prompt (for scripted use)")
    ap.add_argument("--force", action="store_true",
                    help="bypass idempotency check (post even if a prior /watch-video "
                         "comment exists)")
    args = ap.parse_args()

    workdir = Path(args.workdir).resolve()
    if not workdir.exists():
        die(ExitCode.BAD_INPUT, f"workdir not found: {workdir}")
    report_md = workdir / "report.md"
    if not report_md.exists():
        die(ExitCode.BAD_INPUT, f"report.md not found at {report_md} -- "
                                f"run watch_video.py first (without --no-report)")
    meta_path = workdir / "meta.json"
    if not meta_path.exists():
        die(ExitCode.BAD_INPUT, f"meta.json not found at {meta_path}")
    meta = json.loads(meta_path.read_text(encoding="utf-8"))

    # Resolve target Jira key
    if args.jira_key:
        jira_key = args.jira_key
    else:
        jira_key = (meta.get("video") or {}).get("issue_key")
        if not jira_key:
            die(ExitCode.BAD_INPUT,
                "no issue_key in meta.json and --jira-key not provided. "
                "Was this workdir produced from a Jira input?")

    creds = _load_creds(Path(args.credentials))
    auth = _basic_auth(creds["email"], creds["token"])
    site = creds["site"]

    # Build the comment body
    md_text = report_md.read_text(encoding="utf-8")
    adf = md_to_adf(md_text)
    body_str = json.dumps(adf, indent=2)
    body_chars = len(md_text)

    emit("start", step="post_to_jira",
         issue_key=jira_key, site=site,
         body_chars=body_chars, dry_run=args.dry_run)

    # Idempotency check: scan recent comments
    if not args.force and not args.dry_run:
        recent = fetch_recent_comments(site, jira_key, auth)
        for c in recent:
            if comment_contains_signature(c, SIGNATURE):
                emit("warning", step="post_to_jira",
                     msg=f"signature '{SIGNATURE}' found in a recent comment on {jira_key}; "
                         f"skipping to avoid duplicate. Use --force to override.",
                     existing_comment_id=c.get("id"),
                     existing_comment_author=(c.get("author") or {}).get("displayName"))
                print(json.dumps({
                    "status": "skipped_duplicate",
                    "issue_key": jira_key,
                    "existing_comment_id": c.get("id"),
                }))
                return ExitCode.OK

    # Preview block (always show before posting)
    preview_lines = md_text.splitlines()
    print("=" * 72, file=sys.stderr)
    print(f"Target issue : {jira_key}", file=sys.stderr)
    print(f"Site         : https://{site}/browse/{jira_key}", file=sys.stderr)
    print(f"Body size    : {body_chars} chars, {len(adf['content'])} ADF blocks",
          file=sys.stderr)
    print(f"First 3 lines of comment:", file=sys.stderr)
    for line in preview_lines[:3]:
        print(f"  {line[:100]}", file=sys.stderr)
    print(f"...", file=sys.stderr)
    print(f"Last 2 lines of comment:", file=sys.stderr)
    for line in preview_lines[-2:]:
        print(f"  {line[:100]}", file=sys.stderr)
    print("=" * 72, file=sys.stderr)

    if args.dry_run:
        emit("complete", step="post_to_jira", dry_run=True,
             would_post_to=jira_key)
        print(json.dumps({"status": "dry_run", "issue_key": jira_key,
                          "body_chars": body_chars}))
        return ExitCode.OK

    # Interactive confirmation unless --yes
    if not args.yes:
        # If stdin isn't a TTY (e.g., orchestrated from a subprocess), abort
        # with an informative message instead of hanging.
        if not sys.stdin.isatty():
            die(ExitCode.BAD_INPUT,
                "interactive confirmation required but stdin is not a TTY. "
                "Either run interactively or pass --yes (only with explicit "
                "user authorization for this specific post).")
        print(f"\nAbout to POST a comment to {jira_key}. Type 'yes' to confirm: ",
              file=sys.stderr, end="", flush=True)
        answer = sys.stdin.readline().strip().lower()
        if answer != "yes":
            print("Aborted.", file=sys.stderr)
            return ExitCode.OK

    # Post
    t0 = time.time()
    result = post_comment(site, jira_key, auth, adf)
    emit("complete", step="post_to_jira",
         duration_seconds=round(time.time() - t0, 2),
         comment_id=result.get("id"),
         issue_key=jira_key)

    print(json.dumps({
        "status": "posted",
        "issue_key": jira_key,
        "comment_id": result.get("id"),
        "comment_url": f"https://{site}/browse/{jira_key}?focusedCommentId={result.get('id')}",
    }))
    return ExitCode.OK


if __name__ == "__main__":
    sys.exit(main())
