"""Post a workdir's report.md as a comment on the source Jira issue.

This tool DOES NOT RUN unless explicitly invoked by the user. It is never
called automatically by watch_video.py or the orchestrator. The --post-to-jira
flag on watch_video.py is opt-in per run; this standalone script is opt-in
per invocation; and both default to a confirmation prompt before any POST.

Safety stack:
  1. Default off everywhere (watch_video.py won't pass --post-to-jira itself).
  2. --dry-run prints the formatted comment without posting.
  3. Interactive confirmation prompt unless --yes is passed.
  4. Idempotency check: scans recent comments on the ticket for a signature
     that indicates a prior /watch-video post; aborts if found unless --force.
  5. Read-only fallback: any HTTP non-201 -> exit non-zero, no retries.

Usage:
    python post_to_jira.py <workdir> [--jira-key PROJ-X] [--dry-run]
                                     [--yes] [--force]
                                     [--credentials PATH]

The Jira key is read from <workdir>/meta.json's video.issue_key unless
--jira-key is given (which can target a different ticket).
"""
from __future__ import annotations

import argparse
import base64
import json
import re
import sys
import time
import urllib.error
import urllib.request
import uuid
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _common import ExitCode, die, emit  # noqa: E402


DEFAULT_CREDS_PATH = Path.home() / ".atlassian-token" / "credentials.json"
SIGNATURE = "Generated by `/watch-video`"  # appears in report.md footer

# Post styles -- how the comment body is structured on the Jira ticket
STYLE_COLLAPSED = "collapsed"  # default: Timeline section wrapped in ADF expand panel
STYLE_INLINE = "inline"        # legacy v1.5.0: full Timeline shown inline, no expand
STYLE_SUMMARY = "summary"      # short comment with N key moments + report.html attached

# Matches Markdown image refs: ![alt](path)
IMG_REF_RE = re.compile(r"!\[([^\]]*)\]\(([^)]+)\)")
# Matches the media UUID inside a redirect URL like:
#   https://api.media.atlassian.com/file/<uuid>/binary?token=...
MEDIA_UUID_RE = re.compile(r"/file/([a-f0-9-]+)/binary")


def _load_creds(path: Path) -> dict:
    if not path.exists():
        die(ExitCode.BAD_INPUT,
            f"Atlassian credentials not found at {path}",
            credentials_path=str(path),
            hint="See SKILL.md -> Jira token setup")
    return json.loads(path.read_text(encoding="utf-8"))


def _basic_auth(email: str, token: str) -> str:
    return base64.b64encode(f"{email}:{token}".encode()).decode()


def md_to_adf(md_text: str, media_map: dict[str, str] | None = None) -> dict:
    """Minimal markdown-to-ADF converter for Atlassian Cloud comments.

    Handles: # headings (levels 1-6), > blockquotes, image refs (as embedded
    mediaSingle nodes when their filename is in media_map, else italic text),
    --- horizontal rules, blank-line paragraph breaks, plain text.

    When `media_map[filename] = media_uuid` is provided, image markdown
    `![alt](frames/t_001.jpg)` becomes an ADF mediaSingle node referencing
    the media UUID. Otherwise it falls back to italic text mentioning the
    filename (degrades gracefully if attachment upload was skipped/failed).
    """
    media_map = media_map or {}
    content: list[dict] = []
    para_buf: list[str] = []
    quote_buf: list[str] = []
    in_quote = False

    def flush_para():
        if para_buf:
            text = " ".join(s.strip() for s in para_buf if s.strip())
            if text:
                content.append({
                    "type": "paragraph",
                    "content": [{"type": "text", "text": text}],
                })
            para_buf.clear()

    def flush_quote():
        nonlocal in_quote
        if quote_buf:
            text = " ".join(s.strip() for s in quote_buf if s.strip())
            if text:
                content.append({
                    "type": "blockquote",
                    "content": [{
                        "type": "paragraph",
                        "content": [{"type": "text", "text": text}],
                    }],
                })
            quote_buf.clear()
        in_quote = False

    for raw in md_text.split("\n"):
        line = raw.rstrip()

        # Blank line -- end any open block
        if not line.strip():
            flush_para()
            flush_quote()
            continue

        # Heading
        if line.startswith("#"):
            flush_para()
            flush_quote()
            level = 0
            while level < len(line) and line[level] == "#":
                level += 1
            text = line[level:].strip()
            content.append({
                "type": "heading",
                "attrs": {"level": min(max(level, 1), 6)},
                "content": [{"type": "text", "text": text}],
            })
            continue

        # Horizontal rule
        if line.strip() in ("---", "***", "___"):
            flush_para()
            flush_quote()
            content.append({"type": "rule"})
            continue

        # Blockquote
        if line.startswith(">"):
            flush_para()
            in_quote = True
            quote_buf.append(line.lstrip("> ").rstrip())
            continue

        # Image reference -- embed as mediaSingle if we have a media UUID,
        # otherwise fall back to italic text mentioning the filename.
        if line.lstrip().startswith("!["):
            flush_para()
            flush_quote()
            m = IMG_REF_RE.search(line)
            if m and Path(m.group(2)).name in media_map:
                media_uuid = media_map[Path(m.group(2)).name]
                content.append({
                    "type": "mediaSingle",
                    "attrs": {"layout": "center"},
                    "content": [{
                        "type": "media",
                        "attrs": {
                            "type": "file",
                            "id": media_uuid,
                            "collection": "",
                        },
                    }],
                })
            else:
                content.append({
                    "type": "paragraph",
                    "content": [{
                        "type": "text",
                        "text": f"[frame: {line.strip()}]",
                        "marks": [{"type": "em"}],
                    }],
                })
            continue

        # Plain paragraph line
        if in_quote:
            quote_buf.append(line)
        else:
            para_buf.append(line)

    flush_para()
    flush_quote()

    return {"version": 1, "type": "doc", "content": content}


def _extract_image_refs(md_text: str) -> list[tuple[str, str]]:
    """Returns list of (alt, path) tuples for all ![alt](path) markdown refs."""
    return [(m.group(1), m.group(2)) for m in IMG_REF_RE.finditer(md_text)]


def _wrap_timeline_in_expand(adf: dict, expand_title: str) -> dict:
    """Wrap the Timeline section's blocks in an ADF expand node so the ticket
    page shows a single 'click to expand' toggle instead of a wall of frames.

    Finds the heading whose text matches 'Timeline' (or starts with 'Timeline'),
    and the next horizontal rule (the footer separator), then wraps every block
    between them inside an expand node. Heading itself is replaced by the
    expand panel's title.
    """
    blocks = adf.get("content", [])
    timeline_idx = None
    rule_idx = None
    for i, b in enumerate(blocks):
        if b.get("type") == "heading":
            # heading's text is in content[0].text
            text = ""
            for child in b.get("content", []):
                if child.get("type") == "text":
                    text = child.get("text", "").strip()
                    break
            if text.lower().startswith("timeline"):
                timeline_idx = i
        elif b.get("type") == "rule" and timeline_idx is not None and rule_idx is None:
            rule_idx = i
            break
    if timeline_idx is None:
        return adf  # nothing to wrap
    end = rule_idx if rule_idx is not None else len(blocks)
    inner = blocks[timeline_idx + 1 : end]  # skip the original Timeline heading
    if not inner:
        return adf
    expand_node = {
        "type": "expand",
        "attrs": {"title": expand_title},
        "content": inner,
    }
    new_blocks = blocks[:timeline_idx] + [expand_node] + blocks[end:]
    return {**adf, "content": new_blocks}


def _pick_summary_indices(paragraph_count: int, n: int) -> list[int]:
    """Pick N evenly-distributed indices into a paragraph list.
    For N=3 and 67 paragraphs: returns [0, 33, 66] -- first, middle, last.
    For N=1: returns [0].
    """
    if paragraph_count <= 0:
        return []
    if n <= 1:
        return [0]
    if n >= paragraph_count:
        return list(range(paragraph_count))
    return [round(i * (paragraph_count - 1) / (n - 1)) for i in range(n)]


def _load_highlights_indices(workdir: Path, md_text: str) -> list[int] | None:
    """If highlights.json exists, map its picked timestamps back to paragraph
    indices in the markdown so summary mode shows the LLM-picked moments.
    Returns None if no highlights file (caller falls back to even distribution).
    """
    hl_path = workdir / "highlights.json"
    if not hl_path.exists():
        return None
    try:
        hl = json.loads(hl_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None
    picks = hl.get("highlights") or []
    if not picks:
        return None

    # Walk md_text's "### MM:SS" headings to get paragraph indices
    heading_re = re.compile(r"^### (\d{1,2}):(\d{2})", re.MULTILINE)
    timestamps_in_order: list[str] = []
    for m in heading_re.finditer(md_text):
        timestamps_in_order.append(f"{int(m.group(1)):02d}:{m.group(2)}")

    indices: list[int] = []
    for p in picks:
        ts = p.get("timestamp", "")
        m = re.match(r"^(\d{1,2}):(\d{2})$", ts)
        if not m:
            continue
        normalized = f"{int(m.group(1)):02d}:{m.group(2)}"
        if normalized in timestamps_in_order:
            indices.append(timestamps_in_order.index(normalized))
    # Dedup, sort
    seen: set[int] = set()
    ordered: list[int] = []
    for i in sorted(indices):
        if i not in seen:
            seen.add(i)
            ordered.append(i)
    return ordered or None


def _build_summary_markdown(md_text: str, key_indices: list[int],
                            total_paragraph_count: int,
                            html_filename: str | None) -> str:
    """Build a shorter markdown by keeping only key timeline moments.

    Parses the source markdown structure (which our report.md follows reliably)
    and reassembles a summary version: header + source block + N key moments +
    a footer pointer to the attached HTML.
    """
    import re
    # Find the Timeline section
    parts = md_text.split("\n## Timeline\n", 1)
    if len(parts) != 2:
        return md_text  # fallback: structure not recognised, post original
    pre_timeline = parts[0]
    timeline_body = "\n## Timeline\n" + parts[1]

    # Extract each moment block (### MM:SS ... up to next ### or footer)
    moment_re = re.compile(r"(### \d+:\d+.*?)(?=\n### \d+:\d+|\n---|$)", re.DOTALL)
    moments = moment_re.findall(timeline_body)
    if not moments:
        return md_text

    selected = [moments[i] for i in key_indices if 0 <= i < len(moments)]
    summary_timeline = (
        f"\n## Key moments ({len(selected)} of {total_paragraph_count})\n\n"
        + "\n\n".join(m.rstrip() for m in selected)
    )
    if html_filename:
        summary_timeline += (
            f"\n\n---\n\n"
            f"For the full {total_paragraph_count}-frame timeline with transcript "
            f"and on-screen text, open **`{html_filename}`** attached to this issue.\n"
        )
    # Preserve the trailing "Generated by..." footer
    footer_match = re.search(r"\n---\n_Generated by.*", md_text, re.DOTALL)
    footer = footer_match.group(0) if footer_match else ""

    return pre_timeline + summary_timeline + footer


def upload_attachments(file_paths: list[Path], site: str, jira_key: str,
                       auth: str) -> list[dict]:
    """Upload multiple files as Jira issue attachments in one multipart POST.
    Returns the array of attachment records from the response, or [] on 403."""
    url = f"https://{site}/rest/api/3/issue/{jira_key}/attachments"
    boundary = f"watch-video-{uuid.uuid4().hex}"
    parts: list[bytes] = []
    for path in file_paths:
        mime = "image/jpeg" if path.suffix.lower() in (".jpg", ".jpeg") else "application/octet-stream"
        parts.append(f"--{boundary}\r\n".encode())
        parts.append(
            f'Content-Disposition: form-data; name="file"; filename="{path.name}"\r\n'.encode()
        )
        parts.append(f"Content-Type: {mime}\r\n\r\n".encode())
        parts.append(path.read_bytes())
        parts.append(b"\r\n")
    parts.append(f"--{boundary}--\r\n".encode())
    body = b"".join(parts)

    req = urllib.request.Request(url, data=body, headers={
        "Authorization": f"Basic {auth}",
        "Content-Type": f"multipart/form-data; boundary={boundary}",
        # X-Atlassian-Token: no-check is required for attachment endpoints
        # (CSRF bypass for API auth)
        "X-Atlassian-Token": "no-check",
        "Accept": "application/json",
    })
    try:
        with urllib.request.urlopen(req, timeout=180) as resp:
            return json.load(resp)
    except urllib.error.HTTPError as e:
        body_txt = e.read().decode()[:400]
        if e.code == 403:
            emit("warning", step="upload_attachments",
                 msg=f"403 from Atlassian on {jira_key}/attachments; user likely "
                     f"lacks the 'Add attachments' permission. Falling back to "
                     f"text-only comment.",
                 jira_key=jira_key)
            return []
        if e.code == 401:
            die(ExitCode.AUTH_FAIL, "Atlassian auth failed uploading attachments (401)")
        die(ExitCode.IO_FAIL, f"attachment upload failed {e.code}: {body_txt}")


def resolve_media_uuid(jira_attachment_id: str, site: str, auth: str) -> str | None:
    """Get the media-services UUID for a Jira attachment.

    The /attachment/content/<id> endpoint 302-redirects to api.media.atlassian.com
    with the UUID in the path. urllib auto-follows; we read the final URL.
    """
    url = f"https://{site}/rest/api/3/attachment/content/{jira_attachment_id}"
    req = urllib.request.Request(url, headers={"Authorization": f"Basic {auth}"})
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            final_url = resp.url or ""
            m = MEDIA_UUID_RE.search(final_url)
            return m.group(1) if m else None
    except urllib.error.HTTPError as e:
        emit("warning", step="resolve_media_uuid",
             msg=f"could not resolve media UUID for attachment {jira_attachment_id}: {e}",
             attachment_id=jira_attachment_id)
        return None


def build_media_map(report_md_text: str, workdir: Path, site: str,
                    jira_key: str, auth: str) -> dict[str, str]:
    """Uploads referenced frames and returns {filename: media_uuid} map.

    Returns empty dict on permission failure (caller falls back to text refs).
    """
    refs = _extract_image_refs(report_md_text)
    frame_paths: list[Path] = []
    seen: set[str] = set()
    for alt, path in refs:
        p = (workdir / path).resolve()
        if p.exists() and p.name not in seen:
            frame_paths.append(p)
            seen.add(p.name)
    if not frame_paths:
        return {}

    emit("start", step="upload_attachments",
         issue_key=jira_key, count=len(frame_paths))
    t0 = time.time()
    uploaded = upload_attachments(frame_paths, site, jira_key, auth)
    if not uploaded:
        # 403 fallback or no files
        return {}

    media_map: dict[str, str] = {}
    for att in uploaded:
        uuid_str = resolve_media_uuid(att["id"], site, auth)
        if uuid_str:
            media_map[att["filename"]] = uuid_str
    emit("complete", step="upload_attachments",
         duration_seconds=round(time.time() - t0, 2),
         uploaded=len(uploaded), with_media_uuid=len(media_map))
    return media_map


def fetch_recent_comments(site: str, jira_key: str, auth: str,
                          max_results: int = 50) -> list[dict]:
    url = (f"https://{site}/rest/api/3/issue/{jira_key}/comment"
           f"?maxResults={max_results}&orderBy=-created")
    req = urllib.request.Request(url, headers={
        "Authorization": f"Basic {auth}", "Accept": "application/json",
    })
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.load(resp)
    except urllib.error.HTTPError as e:
        if e.code == 401:
            die(ExitCode.AUTH_FAIL, "Atlassian auth failed (401)")
        if e.code == 404:
            die(ExitCode.BAD_INPUT, f"Issue {jira_key} not found or no access")
        die(ExitCode.IO_FAIL, f"Atlassian API {e.code}: {e.read().decode()[:200]}")
    return data.get("comments", [])


def comment_contains_signature(comment: dict, signature: str) -> bool:
    """Walk a comment's ADF body looking for our signature in any text node."""
    body = comment.get("body")
    if isinstance(body, str):
        return signature in body
    # Walk ADF
    stack = [body]
    while stack:
        node = stack.pop()
        if isinstance(node, dict):
            if node.get("type") == "text" and signature in node.get("text", ""):
                return True
            for child in node.get("content", []) or []:
                stack.append(child)
        elif isinstance(node, list):
            stack.extend(node)
    return False


def post_comment(site: str, jira_key: str, auth: str, adf_body: dict) -> dict:
    url = f"https://{site}/rest/api/3/issue/{jira_key}/comment"
    payload = json.dumps({"body": adf_body}).encode()
    req = urllib.request.Request(url, data=payload, headers={
        "Authorization": f"Basic {auth}",
        "Accept": "application/json",
        "Content-Type": "application/json",
    })
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            return json.load(resp)
    except urllib.error.HTTPError as e:
        body = e.read().decode()[:400]
        if e.code == 401:
            die(ExitCode.AUTH_FAIL, f"Atlassian auth failed posting comment: {body}")
        if e.code == 404:
            die(ExitCode.BAD_INPUT, f"Issue {jira_key} not found or no access: {body}")
        die(ExitCode.IO_FAIL, f"Atlassian comment POST failed {e.code}: {body}")


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Post <workdir>/report.md as a comment on a Jira issue. "
                    "Default safety: confirmation prompt + idempotency check.")
    ap.add_argument("workdir")
    ap.add_argument("--jira-key", default=None,
                    help="override the issue key from meta.json's video.issue_key")
    ap.add_argument("--credentials", default=str(DEFAULT_CREDS_PATH),
                    help="Atlassian credentials JSON path")
    ap.add_argument("--dry-run", action="store_true",
                    help="print the formatted comment + target ticket; do NOT post")
    ap.add_argument("--yes", action="store_true",
                    help="skip the interactive confirmation prompt (for scripted use)")
    ap.add_argument("--force", action="store_true",
                    help="bypass idempotency check (post even if a prior /watch-video "
                         "comment exists)")
    ap.add_argument("--no-embed-images", action="store_true",
                    help="skip image embedding; reference frames as text in the comment "
                         "(image embedding is on by default, requires Add Attachments "
                         "permission on the project)")
    ap.add_argument("--style", choices=(STYLE_COLLAPSED, STYLE_INLINE, STYLE_SUMMARY),
                    default=STYLE_COLLAPSED,
                    help="comment layout: 'collapsed' (default) wraps the timeline in "
                         "an ADF expand panel; 'inline' shows the full timeline expanded "
                         "(legacy v1.5.0 behavior); 'summary' posts only N key moments "
                         "and attaches report.html as a downloadable artifact.")
    ap.add_argument("--summary-key-frames", type=int, default=3,
                    help="--style summary only: how many timeline moments to include "
                         "in the comment (default 3, evenly distributed: first, middle, "
                         "last for N=3)")
    args = ap.parse_args()

    workdir = Path(args.workdir).resolve()
    if not workdir.exists():
        die(ExitCode.BAD_INPUT, f"workdir not found: {workdir}")
    report_md = workdir / "report.md"
    if not report_md.exists():
        die(ExitCode.BAD_INPUT, f"report.md not found at {report_md} -- "
                                f"run watch_video.py first (without --no-report)")
    meta_path = workdir / "meta.json"
    if not meta_path.exists():
        die(ExitCode.BAD_INPUT, f"meta.json not found at {meta_path}")
    meta = json.loads(meta_path.read_text(encoding="utf-8"))

    # Resolve target Jira key
    if args.jira_key:
        jira_key = args.jira_key
    else:
        jira_key = (meta.get("video") or {}).get("issue_key")
        if not jira_key:
            die(ExitCode.BAD_INPUT,
                "no issue_key in meta.json and --jira-key not provided. "
                "Was this workdir produced from a Jira input?")

    creds = _load_creds(Path(args.credentials))
    auth = _basic_auth(creds["email"], creds["token"])
    site = creds["site"]

    # Build the comment body
    md_text_full = report_md.read_text(encoding="utf-8")
    total_paragraphs = len(_extract_image_refs(md_text_full))  # one image per moment

    # Summary mode rewrites the markdown to a shorter version with N moments
    # and attaches report.html as a ticket artifact.
    # If <workdir>/highlights.json exists (from highlights.py), we use the
    # LLM-picked moments instead of evenly-distributed indices.
    html_filename = "report.html"
    moment_source = "evenly-distributed"
    if args.style == STYLE_SUMMARY:
        llm_indices = _load_highlights_indices(workdir, md_text_full)
        if llm_indices:
            key_indices = llm_indices
            moment_source = f"llm-picked (highlights.json, {len(llm_indices)} moments)"
        else:
            key_indices = _pick_summary_indices(total_paragraphs, args.summary_key_frames)
        md_text = _build_summary_markdown(
            md_text_full, key_indices, total_paragraphs, html_filename,
        )
    else:
        md_text = md_text_full

    body_chars = len(md_text)

    emit("start", step="post_to_jira",
         issue_key=jira_key, site=site,
         body_chars=body_chars, dry_run=args.dry_run,
         embed_images=(not args.no_embed_images),
         style=args.style,
         key_frames=(args.summary_key_frames if args.style == STYLE_SUMMARY else None))

    # Idempotency check FIRST -- before any uploads. If signature found we
    # abort without writing anything (no comment, no attachments).
    if not args.force and not args.dry_run:
        recent = fetch_recent_comments(site, jira_key, auth)
        for c in recent:
            if comment_contains_signature(c, SIGNATURE):
                emit("warning", step="post_to_jira",
                     msg=f"signature '{SIGNATURE}' found in a recent comment on {jira_key}; "
                         f"skipping to avoid duplicate. Use --force to override.",
                     existing_comment_id=c.get("id"),
                     existing_comment_author=(c.get("author") or {}).get("displayName"))
                print(json.dumps({
                    "status": "skipped_duplicate",
                    "issue_key": jira_key,
                    "existing_comment_id": c.get("id"),
                }))
                return ExitCode.OK

    # Planning phase: enumerate what WOULD be uploaded + build a preview ADF
    # with placeholder UUIDs. No writes happen until after the confirmation
    # gate below. This is the critical safety property: declining the prompt
    # must leave the ticket untouched (no orphan attachments).
    referenced_image_refs = (
        _extract_image_refs(md_text) if not args.no_embed_images else []
    )
    unique_fnames: list[str] = []
    for _, path in referenced_image_refs:
        fname = Path(path).name
        if fname not in unique_fnames:
            unique_fnames.append(fname)

    # `should_upload_report_html` is the INTENT: what a real summary post
    # would do (style + file exists). `will_upload_report_html` adds the
    # dry-run gate -- True only if we'd actually upload on THIS invocation.
    # The preview/dry-run output must report intent (should_*) so users see
    # an honest picture of a real run.
    should_upload_report_html = (
        args.style == STYLE_SUMMARY
        and (workdir / "report.html").exists()
    )
    will_upload_report_html = should_upload_report_html and not args.dry_run
    planned_frame_uploads = len(unique_fnames)
    planned_total_uploads = (
        planned_frame_uploads + (1 if should_upload_report_html else 0)
    )

    # Build preview ADF with placeholder media UUIDs so the structure (and
    # embedded_count) is accurate without touching Jira. Dry-run uses the same
    # placeholder path -- there's no longer a real-vs-fake distinction here.
    preview_media_map: dict[str, str] = {}
    for fname in unique_fnames:
        preview_media_map[fname] = f"PREVIEW-UUID-{len(preview_media_map)+1:04d}"

    def _build_full_adf(media_map: dict[str, str]) -> dict:
        adf_local = md_to_adf(md_text, media_map=media_map)
        if args.style == STYLE_COLLAPSED:
            expand_title = (
                f"Full timeline ({total_paragraphs} frames + transcript)"
                if total_paragraphs else "Full timeline"
            )
            adf_local = _wrap_timeline_in_expand(adf_local, expand_title)
        return adf_local

    preview_adf = _build_full_adf(preview_media_map)

    embedded_count = 0
    def _count_media(blocks):
        nonlocal embedded_count
        for b in blocks:
            if b.get("type") == "mediaSingle":
                embedded_count += 1
            if isinstance(b.get("content"), list):
                _count_media(b["content"])
    _count_media(preview_adf.get("content", []))

    # Preview block (always show before any write)
    preview_lines = md_text.splitlines()
    print("=" * 72, file=sys.stderr)
    print(f"Target issue   : {jira_key}", file=sys.stderr)
    print(f"Site           : https://{site}/browse/{jira_key}", file=sys.stderr)
    print(f"Style          : {args.style}", file=sys.stderr)
    if args.style == STYLE_SUMMARY:
        print(f"Key frames     : {len(key_indices)} of {total_paragraphs} total moments "
              f"({moment_source})", file=sys.stderr)
    print(f"Body size      : {body_chars} chars, {len(preview_adf['content'])} top-level ADF blocks",
          file=sys.stderr)
    print(f"Embedded images: {embedded_count} mediaSingle nodes",
          file=sys.stderr)
    print(f"Will upload    : {planned_total_uploads} file(s) "
          f"({planned_frame_uploads} frame(s)"
          + (" + report.html" if should_upload_report_html else "")
          + ")", file=sys.stderr)
    print(f"First 3 lines of comment:", file=sys.stderr)
    for line in preview_lines[:3]:
        print(f"  {line[:100]}", file=sys.stderr)
    print(f"...", file=sys.stderr)
    print(f"Last 2 lines of comment:", file=sys.stderr)
    for line in preview_lines[-2:]:
        print(f"  {line[:100]}", file=sys.stderr)
    print("=" * 72, file=sys.stderr)

    if args.dry_run:
        emit("complete", step="post_to_jira", dry_run=True,
             would_post_to=jira_key,
             would_upload_frames=planned_frame_uploads,
             would_upload_report_html=should_upload_report_html,
             would_embed_images=embedded_count)
        print(json.dumps({"status": "dry_run", "issue_key": jira_key,
                          "body_chars": body_chars,
                          "adf_blocks": len(preview_adf["content"]),
                          "embedded_images": embedded_count,
                          "planned_upload_count": planned_total_uploads}))
        return ExitCode.OK

    # Interactive confirmation BEFORE any write (uploads or post).
    # If declined, the ticket stays completely untouched -- no orphan
    # attachments, no partial state.
    if not args.yes:
        if not sys.stdin.isatty():
            die(ExitCode.BAD_INPUT,
                "interactive confirmation required but stdin is not a TTY. "
                "Either run interactively or pass --yes (only with explicit "
                "user authorization for this specific post).")
        print(f"\nAbout to upload {planned_total_uploads} file(s) and POST a "
              f"comment to {jira_key}. Type 'yes' to confirm: ",
              file=sys.stderr, end="", flush=True)
        answer = sys.stdin.readline().strip().lower()
        if answer != "yes":
            print("Aborted. Ticket left untouched.", file=sys.stderr)
            return ExitCode.OK

    # ===== Confirmation passed -- writes begin here =====

    # Upload frame attachments and resolve real media UUIDs.
    media_map: dict[str, str] = {}
    if not args.no_embed_images and unique_fnames:
        media_map = build_media_map(md_text, workdir, site, jira_key, auth)

    # Summary mode: upload report.html so readers can download the full report.
    if will_upload_report_html:
        html_path = workdir / "report.html"
        emit("start", step="upload_html", filename=str(html_path.name),
             size_bytes=html_path.stat().st_size)
        upload_attachments([html_path], site, jira_key, auth)
        emit("complete", step="upload_html")

    # Rebuild ADF with real media UUIDs and the same wrap-expand post-process.
    adf = _build_full_adf(media_map)

    # Post
    t0 = time.time()
    result = post_comment(site, jira_key, auth, adf)
    emit("complete", step="post_to_jira",
         duration_seconds=round(time.time() - t0, 2),
         comment_id=result.get("id"),
         issue_key=jira_key)

    print(json.dumps({
        "status": "posted",
        "issue_key": jira_key,
        "comment_id": result.get("id"),
        "comment_url": f"https://{site}/browse/{jira_key}?focusedCommentId={result.get('id')}",
    }))
    return ExitCode.OK


if __name__ == "__main__":
    sys.exit(main())
